linters:
  disable-all: true
  enable:
    - asciicheck
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - whitespace
    - unused

linters-settings:
  lll:
    line-length: 130
  funlen:
    lines: 150
    statements: 80
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/forward32/blank)
